# Sentiment Analysis:

In [2]:
import pandas as pd
from transformers import pipeline
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [3]:
books = pd.read_csv("books_with_filled_categories_2way.csv")
books.head(5)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_category
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction

In [4]:
classifier = pipeline(
    task="text-classification", model="SamLowe/roberta-base-go_emotions", top_k=None
)

Device set to use cpu

In [5]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [6]:
classifier(books["description"][0])

[[{'label': 'neutral', 'score': 0.48206523060798645},
  {'label': 'sadness', 'score': 0.09990349411964417},
  {'label': 'admiration', 'score': 0.0949402004480362},
  {'label': 'approval', 'score': 0.06846719235181808},
  {'label': 'joy', 'score': 0.036704618483781815},
  {'label': 'realization', 'score': 0.0256675872951746},
  {'label': 'disappointment', 'score': 0.02290516532957554},
  {'label': 'caring', 'score': 0.010355038568377495},
  {'label': 'relief', 'score': 0.00962990801781416},
  {'label': 'annoyance', 'score': 0.00626142555847764},
  {'label': 'optimism', 'score': 0.006212254520505667},
  {'label': 'excitement', 'score': 0.00610070675611496},
  {'label': 'grief', 'score': 0.005787441041320562},
  {'label': 'pride', 'score': 0.005556587595492601},
  {'label': 'desire', 'score': 0.004682675935328007},
  {'label': 'nervousness', 'score': 0.0037901881150901318},
  {'label': 'disapproval', 'score': 0.003336822846904397},
  {'label': 'love', 'score': 0.003214040771126747},
  {'label': 'fear', 'score': 0.003056787885725498},
  {'label': 'amusement', 'score': 0.0022629189770668745},
  {'label': 'disgust', 'score': 0.0014760723570361733},
  {'label': 'surprise', 'score': 0.0012264830293133855},
  {'label': 'anger', 'score': 0.000988599262200296},
  {'label': 'embarrassment', 'score': 0.0009525737841613591},
  {'label': 'remorse', 'score': 0.0009374347282573581},
  {'label': 'curiosity', 'score': 0.0007846521330066025},
  {'label': 'gratitude', 'score': 0.0007571439491584897},
  {'label': 'confusion', 'score': 0.000617663492448628}]]

### Sentence based:

In [7]:
classifier(books["description"][0].split("."))

[[{'label': 'excitement', 'score': 0.49505022168159485},
  {'label': 'admiration', 'score': 0.29842233657836914},
  {'label': 'neutral', 'score': 0.11334917694330215},
  {'label': 'approval', 'score': 0.061566535383462906},
  {'label': 'surprise', 'score': 0.02545263059437275},
  {'label': 'curiosity', 'score': 0.020611140877008438},
  {'label': 'joy', 'score': 0.013649091124534607},
  {'label': 'love', 'score': 0.012229564599692822},
  {'label': 'desire', 'score': 0.012063329108059406},
  {'label': 'optimism', 'score': 0.005851092282682657},
  {'label': 'realization', 'score': 0.004697063472121954},
  {'label': 'annoyance', 'score': 0.002989332191646099},
  {'label': 'pride', 'score': 0.00259979534894228},
  {'label': 'confusion', 'score': 0.002407281892374158},
  {'label': 'amusement', 'score': 0.00219554640352726},
  {'label': 'disapproval', 'score': 0.0021141960751265287},
  {'label': 'disappointment', 'score': 0.001981467241421342},
  {'label': 'disgust', 'score': 0.0014362828806042671},
  {'label': 'fear', 'score': 0.0014153314987197518},
  {'label': 'anger', 'score': 0.001288198516704142},
  {'label': 'caring', 'score': 0.0011934032663702965},
  {'label': 'sadness', 'score': 0.001169282477349043},
  {'label': 'gratitude', 'score': 0.0008985294844023883},
  {'label': 'relief', 'score': 0.0008879491942934692},
  {'label': 'nervousness', 'score': 0.0006956638535484672},
  {'label': 'embarrassment', 'score': 0.0004494803724810481},
  {'label': 'grief', 'score': 0.0004383956256788224},
  {'label': 'remorse', 'score': 0.00024301867233589292}],
 [{'label': 'neutral', 'score': 0.9304519891738892},
  {'label': 'approval', 'score': 0.032577622681856155},
  {'label': 'realization', 'score': 0.01269619632512331},
  {'label': 'admiration', 'score': 0.009453446604311466},
  {'label': 'annoyance', 'score': 0.006214239168912172},
  {'label': 'disapproval', 'score': 0.002901130821555853},
  {'label': 'disappointment', 'score': 0.0026528954040259123},
  {'label': 'optimism', 'score': 0.0019252232741564512},
  {'label': 'amusement', 'score': 0.0017451095627620816},
  {'label': 'disgust', 'score': 0.0016568925930187106},
  {'label': 'confusion', 'score': 0.0016196827637031674},
  {'label': 'sadness', 'score': 0.0014964565634727478},
  {'label': 'anger', 'score': 0.0014913077466189861},
  {'label': 'joy', 'score': 0.0013627652078866959},
  {'label': 'excitement', 'score': 0.0010866299271583557},
  {'label': 'gratitude', 'score': 0.0009999173926189542},
  {'label': 'love', 'score': 0.0009145583608187735},
  {'label': 'fear', 'score': 0.0008080736151896417},
  {'label': 'curiosity', 'score': 0.000741883646696806},
  {'label': 'surprise', 'score': 0.0006469803629443049},
  {'label': 'caring', 'score': 0.0006131516420282423},
  {'label': 'desire', 'score': 0.0004939803620800376},
  {'label': 'pride', 'score': 0.0004914430901408195},
  {'label': 'embarrassment', 'score': 0.0004754800465889275},
  {'label': 'relief', 'score': 0.00038349098758772016},
  {'label': 'remorse', 'score': 0.0002674514544196427},
  {'label': 'grief', 'score': 0.0002609098155517131},
  {'label': 'nervousness', 'score': 0.00018528845976106822}],
 [{'label': 'neutral', 'score': 0.9456536769866943},
  {'label': 'realization', 'score': 0.030264288187026978},
  {'label': 'approval', 'score': 0.022307079285383224},
  {'label': 'sadness', 'score': 0.008609036915004253},
  {'label': 'disappointment', 'score': 0.008574128150939941},
  {'label': 'disapproval', 'score': 0.006441464181989431},
  {'label': 'annoyance', 'score': 0.005673831794410944},
  {'label': 'optimism', 'score': 0.0033504520542919636},
  {'label': 'admiration', 'score': 0.0029649834614247084},
  {'label': 'confusion', 'score': 0.0022469533141702414},
  {'label': 'joy', 'score': 0.0019315161043778062},
  {'label': 'fear', 'score': 0.0017752174753695726},
  {'label': 'amusement', 'score': 0.0016993120079860091},
  {'label': 'disgust', 'score': 0.001639124471694231},
  {'label': 'caring', 'score': 0.0015369165921583772},
  {'label': 'gratitude', 'score': 0.0014884894480928779},
  {'label': 'desire', 'score': 0.0014817941701039672},
  {'label': 'excitement', 'score': 0.0010602918919175863},
  {'label': 'anger', 'score': 0.0010424380889162421},
  {'label': 'relief', 'score': 0.001034842338413},
  {'label': 'love', 'score': 0.0010253525106236339},
  {'label': 'surprise', 'score': 0.0009858707198873162},
  {'label': 'embarrassment', 'score': 0.0009728080476634204},
  {'label': 'grief', 'score': 0.0009689632570371032},
  {'label': 'remorse', 'score': 0.0009397831163369119},
  {'label': 'curiosity', 'score': 0.0008562362636439502},
  {'label': 'nervousness', 'score': 0.0006771045736968517},
  {'label': 'pride', 'score': 0.0005158283747732639}],
 [{'label': 'neutral', 'score': 0.9423111081123352},
  {'label': 'approval', 'score': 0.03423650562763214},
  {'label': 'realization', 'score': 0.024165300652384758},
  {'label': 'annoyance', 'score': 0.006766465026885271},
  {'label': 'admiration', 'score': 0.005985395051538944},
  {'label': 'sadness', 'score': 0.005476183723658323},
  {'label': 'disappointment', 'score': 0.004732142668217421},
  {'label': 'optimism', 'score': 0.003723397385329008},
  {'label': 'disapproval', 'score': 0.0034888640511780977},
  {'label': 'disgust', 'score': 0.002289119642227888},
  {'label': 'fear', 'score': 0.0019254935905337334},
  {'label': 'anger', 'score': 0.0016113449819386005},
  {'label': 'confusion', 'score': 0.0015487560303881764},
  {'label': 'desire', 'score': 0.0014074394712224603},
  {'label': 'caring', 'score': 0.0013327649794518948},
  {'label': 'amusement', 'score': 0.0012335136998444796},
  {'label': 'joy', 'score': 0.0011541952844709158},
  {'label': 'gratitude', 'score': 0.0011314431903883815},
  {'label': 'excitement', 'score': 0.0009034093236550689},
  {'label': 'curiosity', 'score': 0.0008207110222429037},
  {'label': 'love', 'score': 0.0008027010480873287},
  {'label': 'surprise', 'score': 0.0007140392553992569},
  {'label': 'grief', 'score': 0.0007081411313265562},
  {'label': 'embarrassment', 'score': 0.0006961351609788835},
  {'label': 'relief', 'score': 0.0006308657466433942},
  {'label': 'pride', 'score': 0.0006148181855678558},
  {'label': 'remorse', 'score': 0.0005936574889346957},
  {'label': 'nervousness', 'score': 0.00043113311403431}],
 [{'label': 'sadness', 'score': 0.717038631439209},
  {'label': 'neutral', 'score': 0.22705158591270447},
  {'label': 'disappointment', 'score': 0.037475358694791794},
  {'label': 'caring', 'score': 0.03551090136170387},
  {'label': 'grief', 'score': 0.022810181602835655},
  {'label': 'remorse', 'score': 0.022793447598814964},
  {'label': 'approval', 'score': 0.02110271342098713},
  {'label': 'realization', 'score': 0.020856287330389023},
  {'label': 'nervousness', 'score': 0.009491315111517906},
  {'label': 'desire', 'score': 0.007585064973682165},
  {'label': 'annoyance', 'score': 0.0071655092760920525},
  {'label': 'fear', 'score': 0.005749265197664499},
  {'label': 'love', 'score': 0.0049141887575387955},
  {'label': 'disapproval', 'score': 0.004410536494106054},
  {'label': 'joy', 'score': 0.004319219384342432},
  {'label': 'admiration', 'score': 0.00426640035584569},
  {'label': 'optimism', 'score': 0.003972636070102453},
  {'label': 'relief', 'score': 0.0038718769792467356},
  {'label': 'disgust', 'score': 0.00275519210845232},
  {'label': 'anger', 'score': 0.0027164684142917395},
  {'label': 'embarrassment', 'score': 0.002129608066752553},
  {'label': 'confusion', 'score': 0.001999679720029235},
  {'label': 'amusement', 'score': 0.0018111105309799314},
  {'label': 'curiosity', 'score': 0.0015943987527862191},
  {'label': 'gratitude', 'score': 0.0015786257572472095},
  {'label': 'excitement', 'score': 0.0012141503393650055},
  {'label': 'surprise', 'score': 0.0009485891787335277},
  {'label': 'pride', 'score': 0.0008664469351060688}],
 [{'label': 'joy', 'score': 0.7413577437400818},
  {'label': 'admiration', 'score': 0.17403708398342133},
  {'label': 'approval', 'score': 0.09558126330375671},
  {'label': 'neutral', 'score': 0.07788766175508499},
  {'label': 'excitement', 'score': 0.04985085874795914},
  {'label': 'amusement', 'score': 0.027041394263505936},
  {'label': 'pride', 'score': 0.018388202413916588},
  {'label': 'relief', 'score': 0.017696550115942955},
  {'label': 'love', 'score': 0.012335107661783695},
  {'label': 'annoyance', 'score': 0.011396274901926517},
  {'label': 'realization', 'score': 0.009998851455748081},
  {'label': 'optimism', 'score': 0.008728337474167347},
  {'label': 'caring', 'score': 0.006444095633924007},
  {'label': 'disapproval', 'score': 0.003990003373473883},
  {'label': 'disappointment', 'score': 0.003481761086732149},
  {'label': 'gratitude', 'score': 0.0031221790704876184},
  {'label': 'desire', 'score': 0.0027519124560058117},
  {'label': 'anger', 'score': 0.0024055507965385914},
  {'label': 'sadness', 'score': 0.0024009221233427525},
  {'label': 'surprise', 'score': 0.0015793457860127091},
  {'label': 'nervousness', 'score': 0.00108026631642133},
  {'label': 'grief', 'score': 0.0009937372524291277},
  {'label': 'embarrassment', 'score': 0.0009483267203904688},
  {'label': 'disgust', 'score': 0.000913747469894588},
  {'label': 'curiosity', 'score': 0.0008255878346972167},
  {'label': 'confusion', 'score': 0.0008174817194230855},
  {'label': 'fear', 'score': 0.0006173051078803837},
  {'label': 'remorse', 'score': 0.0003333486965857446}],
 [{'label': 'admiration', 'score': 0.6923783421516418},
  {'label': 'neutral', 'score': 0.1759381741285324},
  {'label': 'approval', 'score': 0.16847151517868042},
  {'label': 'excitement', 'score': 0.03926483914256096},
  {'label': 'surprise', 'score': 0.00880743283778429},
  {'label': 'realization', 'score': 0.008398082107305527},
  {'label': 'optimism', 'score': 0.007704559713602066},
  {'label': 'pride', 'score': 0.0048834774643182755},
  {'label': 'joy', 'score': 0.00467676343396306},
  {'label': 'annoyance', 'score': 0.003625578014180064},
  {'label': 'curiosity', 'score': 0.0033035334199666977},
  {'label': 'love', 'score': 0.0031879961024969816},
  {'label': 'disapproval', 'score': 0.002368830144405365},
  {'label': 'disappointment', 'score': 0.0020747336093336344},
  {'label': 'confusion', 'score': 0.001657560933381319},
  {'label': 'gratitude', 'score': 0.0015371961053460836},
  {'label': 'desire', 'score': 0.0013163572875782847},
  {'label': 'amusement', 'score': 0.0012664974201470613},
  {'label': 'anger', 'score': 0.0009398508118465543},
  {'label': 'caring', 'score': 0.0008626246126368642},
  {'label': 'disgust', 'score': 0.0006821205606684089},
  {'label': 'relief', 'score': 0.000672635214868933},
  {'label': 'fear', 'score': 0.0005614985711872578},
  {'label': 'sadness', 'score': 0.00044334857375361025},
  {'label': 'embarrassment', 'score': 0.00031752907671034336},
  {'label': 'grief', 'score': 0.0002563344605732709},
  {'label': 'nervousness', 'score': 0.00017763077630661428},
  {'label': 'remorse', 'score': 0.00016375313862226903}],
 [{'label': 'neutral', 'score': 0.9549601674079895},
  {'label': 'approval', 'score': 0.022920334711670876},
  {'label': 'disapproval', 'score': 0.009044039063155651},
  {'label': 'realization', 'score': 0.008665132336318493},
  {'label': 'annoyance', 'score': 0.006453514564782381},
  {'label': 'disappointment', 'score': 0.005593900103121996},
  {'label': 'admiration', 'score': 0.004978002514690161},
  {'label': 'sadness', 'score': 0.002301154425367713},
  {'label': 'optimism', 'score': 0.0021426284220069647},
  {'label': 'confusion', 'score': 0.0020893877372145653},
  {'label': 'excitement', 'score': 0.001905130920931697},
  {'label': 'joy', 'score': 0.0016943643568083644},
  {'label': 'anger', 'score': 0.0015344731509685516},
  {'label': 'disgust', 'score': 0.0014689216623082757},
  {'label': 'gratitude', 'score': 0.0013705708552151918},
  {'label': 'amusement', 'score': 0.0010898250620812178},
  {'label': 'fear', 'score': 0.001050855265930295},
  {'label': 'desire', 'score': 0.0010161608224734664},
  {'label': 'curiosity', 'score': 0.0009845246095210314},
  {'label': 'surprise', 'score': 0.0009003458544611931},
  {'label': 'love', 'score': 0.0008973359945230186},
  {'label': 'caring', 'score': 0.0008596849511377513},
  {'label': 'embarrassment', 'score': 0.0006433894159272313},
  {'label': 'relief', 'score': 0.0005002190009690821},
  {'label': 'pride', 'score': 0.0004335331032052636},
  {'label': 'remorse', 'score': 0.0004028224211651832},
  {'label': 'grief', 'score': 0.0003901346353814006},
  {'label': 'nervousness', 'score': 0.00035461969673633575}]]

In [8]:
sentences = books ["description"][0].split(".")
predictions = classifier (sentences)

In [9]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [10]:
predictions[0]

[{'label': 'excitement', 'score': 0.49505022168159485},
 {'label': 'admiration', 'score': 0.29842233657836914},
 {'label': 'neutral', 'score': 0.11334917694330215},
 {'label': 'approval', 'score': 0.061566535383462906},
 {'label': 'surprise', 'score': 0.02545263059437275},
 {'label': 'curiosity', 'score': 0.020611140877008438},
 {'label': 'joy', 'score': 0.013649091124534607},
 {'label': 'love', 'score': 0.012229564599692822},
 {'label': 'desire', 'score': 0.012063329108059406},
 {'label': 'optimism', 'score': 0.005851092282682657},
 {'label': 'realization', 'score': 0.004697063472121954},
 {'label': 'annoyance', 'score': 0.002989332191646099},
 {'label': 'pride', 'score': 0.00259979534894228},
 {'label': 'confusion', 'score': 0.002407281892374158},
 {'label': 'amusement', 'score': 0.00219554640352726},
 {'label': 'disapproval', 'score': 0.0021141960751265287},
 {'label': 'disappointment', 'score': 0.001981467241421342},
 {'label': 'disgust', 'score': 0.0014362828806042671},
 {'label': 'fear', 'score': 0.0014153314987197518},
 {'label': 'anger', 'score': 0.001288198516704142},
 {'label': 'caring', 'score': 0.0011934032663702965},
 {'label': 'sadness', 'score': 0.001169282477349043},
 {'label': 'gratitude', 'score': 0.0008985294844023883},
 {'label': 'relief', 'score': 0.0008879491942934692},
 {'label': 'nervousness', 'score': 0.0006956638535484672},
 {'label': 'embarrassment', 'score': 0.0004494803724810481},
 {'label': 'grief', 'score': 0.0004383956256788224},
 {'label': 'remorse', 'score': 0.00024301867233589292}]

In [11]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [12]:
predictions[3]

[{'label': 'neutral', 'score': 0.9423111081123352},
 {'label': 'approval', 'score': 0.03423650562763214},
 {'label': 'realization', 'score': 0.024165300652384758},
 {'label': 'annoyance', 'score': 0.006766465026885271},
 {'label': 'admiration', 'score': 0.005985395051538944},
 {'label': 'sadness', 'score': 0.005476183723658323},
 {'label': 'disappointment', 'score': 0.004732142668217421},
 {'label': 'optimism', 'score': 0.003723397385329008},
 {'label': 'disapproval', 'score': 0.0034888640511780977},
 {'label': 'disgust', 'score': 0.002289119642227888},
 {'label': 'fear', 'score': 0.0019254935905337334},
 {'label': 'anger', 'score': 0.0016113449819386005},
 {'label': 'confusion', 'score': 0.0015487560303881764},
 {'label': 'desire', 'score': 0.0014074394712224603},
 {'label': 'caring', 'score': 0.0013327649794518948},
 {'label': 'amusement', 'score': 0.0012335136998444796},
 {'label': 'joy', 'score': 0.0011541952844709158},
 {'label': 'gratitude', 'score': 0.0011314431903883815},
 {'label': 'excitement', 'score': 0.0009034093236550689},
 {'label': 'curiosity', 'score': 0.0008207110222429037},
 {'label': 'love', 'score': 0.0008027010480873287},
 {'label': 'surprise', 'score': 0.0007140392553992569},
 {'label': 'grief', 'score': 0.0007081411313265562},
 {'label': 'embarrassment', 'score': 0.0006961351609788835},
 {'label': 'relief', 'score': 0.0006308657466433942},
 {'label': 'pride', 'score': 0.0006148181855678558},
 {'label': 'remorse', 'score': 0.0005936574889346957},
 {'label': 'nervousness', 'score': 0.00043113311403431}]

In [13]:
sorted(predictions[0], key=lambda x: x["label"]) # alphabetical order

[{'label': 'admiration', 'score': 0.29842233657836914},
 {'label': 'amusement', 'score': 0.00219554640352726},
 {'label': 'anger', 'score': 0.001288198516704142},
 {'label': 'annoyance', 'score': 0.002989332191646099},
 {'label': 'approval', 'score': 0.061566535383462906},
 {'label': 'caring', 'score': 0.0011934032663702965},
 {'label': 'confusion', 'score': 0.002407281892374158},
 {'label': 'curiosity', 'score': 0.020611140877008438},
 {'label': 'desire', 'score': 0.012063329108059406},
 {'label': 'disappointment', 'score': 0.001981467241421342},
 {'label': 'disapproval', 'score': 0.0021141960751265287},
 {'label': 'disgust', 'score': 0.0014362828806042671},
 {'label': 'embarrassment', 'score': 0.0004494803724810481},
 {'label': 'excitement', 'score': 0.49505022168159485},
 {'label': 'fear', 'score': 0.0014153314987197518},
 {'label': 'gratitude', 'score': 0.0008985294844023883},
 {'label': 'grief', 'score': 0.0004383956256788224},
 {'label': 'joy', 'score': 0.013649091124534607},
 {'label': 'love', 'score': 0.012229564599692822},
 {'label': 'nervousness', 'score': 0.0006956638535484672},
 {'label': 'neutral', 'score': 0.11334917694330215},
 {'label': 'optimism', 'score': 0.005851092282682657},
 {'label': 'pride', 'score': 0.00259979534894228},
 {'label': 'realization', 'score': 0.004697063472121954},
 {'label': 'relief', 'score': 0.0008879491942934692},
 {'label': 'remorse', 'score': 0.00024301867233589292},
 {'label': 'sadness', 'score': 0.001169282477349043},
 {'label': 'surprise', 'score': 0.02545263059437275}]

In [14]:
emotion_labels = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",
    "neutral",
]
isbn = []

emotion_scores = {label: [] for label in emotion_labels}


def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}

    # predictions = list of lists of dicts
    for pred in predictions:
        for emo in pred:
            label = emo["label"]
            score = emo["score"]
            per_emotion_scores[label].append(score)

    return {
        label: (max(scores) if scores else 0.0)
        for label, scores in per_emotion_scores.items()
    }

In [ ]:
'''for i in range (10):
  isbn.append(books["isbn13"][i])
  sentences = books["description"][i].split(".")
  predictions = classifier(sentences)
  max_scores =  calculate_max_emotion_scores(predictions)
  for label in emotion_labels:
    emotion_scores[label].append(max_scores[label])

emotion_scores'''

In [16]:
from nltk.tokenize import sent_tokenize

for i in range(10):
    isbn.append(books["isbn13"][i])

    # safer sentence splitting
    sentences = sent_tokenize(books["description"][i])
    sentences = [s for s in sentences if len(s.split()) > 3]

    # if no valid sentences, default to neutral
    if not sentences:
        for label in emotion_labels:
            emotion_scores[label].append(0.0)
        emotion_scores["neutral"][-1] = 1.0
        continue

    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)

    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [18]:
emotion_scores

{'admiration': [0.6923783421516418,
  0.8429385423660278,
  0.843847930431366,
  0.21287237107753754,
  0.6245195865631104,
  0.016076944768428802,
  0.8295949101448059,
  0.934485912322998,
  0.05251774936914444,
  0.004978002514690161,
  0.7740874886512756,
  0.8832985162734985,
  0.862983226776123,
  0.23432452976703644,
  0.8568076491355896,
  0.01627143658697605,
  0.8450432419776917,
  0.9390323758125305,
  0.20669059455394745,
  0.004803244955837727],
 'amusement': [0.027041394263505936,
  0.002372277667745948,
  0.0017943853745236993,
  0.001553419278934598,
  0.003031004685908556,
  0.0019459290197119117,
  0.002323702909052372,
  0.012667234055697918,
  0.0025026716757565737,
  0.0027869348414242268,
  0.025068948045372963,
  0.002409779466688633,
  0.0015157979214563966,
  0.0015944449696689844,
  0.0027581797912716866,
  0.0019321709405630827,
  0.0017188942292705178,
  0.01247562188655138,
  0.002366969594731927,
  0.001682234462350607],
 'anger': [0.0027164684142917395,
  0.004283696413040161,
  0.04729504883289337,
  0.013755341991782188,
  0.005192015785723925,
  0.002820813562721014,
  0.00975849200040102,
  0.0029164873994886875,
  0.0044586267322301865,
  0.0032089955639094114,
  0.0028101904317736626,
  0.004790700040757656,
  0.042628638446331024,
  0.011205623857676983,
  0.003022118704393506,
  0.003408033400774002,
  0.009581424295902252,
  0.002891340060159564,
  0.004477221053093672,
  0.0009633728768676519],
 'annoyance': [0.011396274901926517,
  0.015322037041187286,
  0.03773149102926254,
  0.017027726396918297,
  0.011019321158528328,
  0.01937262900173664,
  0.13249444961547852,
  0.006453514564782381,
  0.06916256248950958,
  0.006453514564782381,
  0.009232318960130215,
  0.020327884703874588,
  0.037846196442842484,
  0.015147600322961807,
  0.012655858881771564,
  0.025629587471485138,
  0.13456091284751892,
  0.006990277674049139,
  0.05102360621094704,
  0.004165702499449253],
 'approval': [0.16847151517868042,
  0.06941186636686325,
  0.0675317645072937,
  0.4501335620880127,
  0.3380611836910248,
  0.09100823104381561,
  0.12049921602010727,
  0.058531101793050766,
  0.07161397486925125,
  0.023192673921585083,
  0.16047894954681396,
  0.06546203047037125,
  0.0700305625796318,
  0.4754309356212616,
  0.3573809266090393,
  0.09941719472408295,
  0.17158176004886627,
  0.061024587601423264,
  0.08769471943378448,
  0.025136392563581467],
 'caring': [0.03551090136170387,
  0.003428122727200389,
  0.005412059836089611,
  0.04705003276467323,
  0.17668461799621582,
  0.0010082480730488896,
  0.010578949935734272,
  0.003352319123223424,
  0.004922688473016024,
  0.001087530399672687,
  0.052508436143398285,
  0.003575374139472842,
  0.005493722390383482,
  0.08269350975751877,
  0.1924636960029602,
  0.0011240580352023244,
  0.012187937274575233,
  0.0030128145590424538,
  0.006623789668083191,
  0.0007780486484989524],
 'confusion': [0.002407281892374158,
  0.3190414011478424,
  0.004081385210156441,
  0.005814033560454845,
  0.06191765516996384,
  0.009557390585541725,
  0.03175407275557518,
  0.002799801994115114,
  0.16604258120059967,
  0.0026910884771496058,
  0.0022289452608674765,
  0.4401264786720276,
  0.004085857421159744,
  0.004918242804706097,
  0.10809541493654251,
  0.010757884941995144,
  0.028180468827486038,
  0.0027866060845553875,
  0.1519937366247177,
  0.002602232154458761],
 'curiosity': [0.020611140877008438,
  0.19671237468719482,
  0.0016204154817387462,
  0.0020340755581855774,
  0.2765440344810486,
  0.004658136051148176,
  0.004926599562168121,
  0.002531789243221283,
  0.5579909086227417,
  0.001640548463910818,
  0.017477912828326225,
  0.31999900937080383,
  0.0014326183591037989,
  0.0026036258786916733,
  0.4264003336429596,
  0.003856832627207041,
  0.005160220433026552,
  0.0022417681757360697,
  0.6162864565849304,
  0.0011035652132704854],
 'desire': [0.012063329108059406,
  0.012093991972506046,
  0.003371239174157381,
  0.0030081088189035654,
  0.02769014984369278,
  0.0013568528229370713,
  0.02020108513534069,
  0.005137198138982058,
  0.0026953225024044514,
  0.001150353578850627,
  0.010262144729495049,
  0.020270174369215965,
  0.003704266855493188,
  0.0028870543465018272,
  0.025101255625486374,
  0.0013363613979890943,
  0.015507606789469719,
  0.004598556086421013,
  0.005963394418358803,
  0.0008546399767510593],
 'disappointment': [0.037475358694791794,
  0.008344059810042381,
  0.024637997150421143,
  0.02536569908261299,
  0.01568441651761532,
  0.04987050220370293,
  0.2645466923713684,
  0.009820082224905491,
  0.04592765122652054,
  0.005593900103121996,
  0.03225050866603851,
  0.024230321869254112,
  0.026093659922480583,
  0.013805857859551907,
  0.013699364848434925,
  0.06604800373315811,
  0.33654630184173584,
  0.011819048784673214,
  0.04254237189888954,
  0.004130883142352104],
 'disapproval': [0.009044039063155651,
  0.01069733127951622,
  0.027921970933675766,
  0.03854477033019066,
  0.014112225733697414,
  0.010870863683521748,
  0.25867047905921936,
  0.009044039063155651,
  0.10475357621908188,
  0.009044039063155651,
  0.007913750596344471,
  0.005882376339286566,
  0.03061402030289173,
  0.02892426587641239,
  0.009628195315599442,
  0.01373959332704544,
  0.33125919103622437,
  0.006953047122806311,
  0.1578873097896576,
  0.0032357508316636086],
 'disgust': [0.00275519210845232,
  0.002758268965408206,
  0.010160163044929504,
  0.0075917234644293785,
  0.002779546193778515,
  0.005427450407296419,
  0.005339144263416529,
  0.002167430240660906,
  0.010195432230830193,
  0.0021536066196858883,
  0.004484942648559809,
  0.003446542890742421,
  0.010018237866461277,
  0.005465297494083643,
  0.002318208571523428,
  0.0063695344142615795,
  0.005104925483465195,
  0.002067721216008067,
  0.010205143131315708,
  0.0015903443563729525],
 'embarrassment': [0.002129608066752553,
  0.002137850970029831,
  0.002337123267352581,
  0.0014101751148700714,
  0.0012546859215945005,
  0.003355348715558648,
  0.0043943035416305065,
  0.004756958223879337,
  0.005524119827896357,
  0.0008792559965513647,
  0.0019068632973358035,
  0.006136402487754822,
  0.001932736486196518,
  0.0012422517174854875,
  0.0011778314365074039,
  0.003995861392468214,
  0.003919493872672319,
  0.004979691933840513,
  0.004830246791243553,
  0.0007435635779984295],
 'excitement': [0.49505022168159485,
  0.006602166220545769,
  0.0033774483017623425,
  0.0046555097214877605,
  0.003976118750870228,
  0.005328916013240814,
  0.004053404089063406,
  0.16559652984142303,
  0.004191972315311432,
  0.003698118031024933,
  0.3932342827320099,
  0.006577418651431799,
  0.003385021584108472,
  0.004044887609779835,
  0.003524769563227892,
  0.003767839865759015,
  0.004786026198416948,
  0.11053208261728287,
  0.006029091309756041,
  0.0018007373437285423],
 'fear': [0.005749265197664499,
  0.0077293189242482185,
  0.4297308623790741,
  0.1117163673043251,
  0.0022661960683763027,
  0.0038918806239962578,
  0.1997285783290863,
  0.009991118684411049,
  0.016967134550213814,
  0.0020883993711322546,
  0.007522864732891321,
  0.018172279000282288,
  0.3659707009792328,
  0.08913379907608032,
  0.00205762917175889,
  0.004352685995399952,
  0.24883568286895752,
  0.009201759472489357,
  0.017419323325157166,
  0.0014455333584919572],
 'gratitude': [0.0031221790704876184,
  0.00449849758297205,
  0.002397361444309354,
  0.0018823730060830712,
  0.027513470500707626,
  0.0013705708552151918,
  0.017431538552045822,
  0.020486928522586823,
  0.0017378944903612137,
  0.0013705708552151918,
  0.003743789391592145,
  0.004589700605720282,
  0.003002194222062826,
  0.002256239764392376,
  0.02496642805635929,
  0.0013989713042974472,
  0.017771698534488678,
  0.012877342291176319,
  0.0017365763196721673,
  0.0008606951450929046],
 'grief': [0.022810181602835655,
  0.0020337686873972416,
  0.0013573213946074247,
  0.003092194441705942,
  0.001541474019177258,
  0.002187392907217145,
  0.0017342352075502276,
  0.010866377502679825,
  0.007081227842718363,
  0.0006272930768318474,
  0.023659592494368553,
  0.002211568644270301,
  0.001431571668945253,
  0.0026959404349327087,
  0.0009801082778722048,
  0.002834388753399253,
  0.0017525394214317203,
  0.011513923294842243,
  0.006317928433418274,
  0.00043509851093403995],
 'joy': [0.7413577437400818,
  0.003938138950616121,
  0.002567269606515765,
  0.005266185384243727,
  0.0034977963659912348,
  0.0020171490032225847,
  0.003270617453381419,
  0.31750860810279846,
  0.0026295462157577276,
  0.003894500434398651,
  0.7426798343658447,
  0.003300206735730171,
  0.0020166095346212387,
  0.004431231413036585,
  0.002334090881049633,
  0.0017360001802444458,
  0.002836045576259494,
  0.2945784628391266,
  0.0024591381661593914,
  0.0019529156852513552],
 'love': [0.012335107661783695,
  0.00238038063980639,
  0.040726158767938614,
  0.3779682517051697,
  0.004655490163713694,
  0.0018592153210192919,
  0.0020092776976525784,
  0.004947302863001823,
  0.003767417510971427,
  0.0013717631809413433,
  0.01770293526351452,
  0.0028697361703962088,
  0.042395591735839844,
  0.23777568340301514,
  0.004519565496593714,
  0.0019892039708793163,
  0.002072864444926381,
  0.004319627769291401,
  0.005310963373631239,
  0.0010749947978183627],
 'nervousness': [0.009491315111517906,
  0.0027570740785449743,
  0.012109999544918537,
  0.014452693983912468,
  0.0008792015723884106,
  0.0012335308128967881,
  0.013334467075765133,
  0.009201593697071075,
  0.0037340130656957626,
  0.0005637290305458009,
  0.009589632973074913,
  0.00846796203404665,
  0.009504818357527256,
  0.011858249083161354,
  0.0009730193996801972,
  0.001240984653122723,
  0.015653299167752266,
  0.009577673859894276,
  0.003747280454263091,
  0.00045739003689959645],
 'optimism': [0.008728337474167347,
  0.009755953215062618,
  0.010674944147467613,
  0.010419671423733234,
  0.4493839144706726,
  0.004559605848044157,
  0.11516298353672028,
  0.005373896565288305,
  0.015621394850313663,
  0.002578071551397443,
  0.00865146704018116,
  0.009926099330186844,
  0.011953633278608322,
  0.01274868194013834,
  0.43774256110191345,
  0.004036376718431711,
  0.08790898323059082,
  0.005785696674138308,
  0.016097618266940117,
  0.002644467167556286],
 'pride': [0.018388202413916588,
  0.0037469384260475636,
  0.004599833395332098,
  0.00417657196521759,
  0.004905347712337971,
  0.001667706063017249,
  0.006487663835287094,
  0.0070108394138514996,
  0.0008276246953755617,
  0.0005016230861656368,
  0.02031935565173626,
  0.003875446505844593,
  0.00527328671887517,
  0.005643917713314295,
  0.005499381106346846,
  0.0020380071364343166,
  0.0066488273441791534,
  0.006638822611421347,
  0.0007793389959260821,
  0.0005156341940164566],
 'realization': [0.030264288187026978,
  0.05541609972715378,
  0.029825475066900253,
  0.0927034392952919,
  0.014125892892479897,
  0.1821882724761963,
  0.03183861821889877,
  0.05015353858470917,
  0.030035948380827904,
  0.017598042264580727,
  0.0353141613304615,
  0.04341711103916168,
  0.028677254915237427,
  0.09118534624576569,
  0.015883328393101692,
  0.20016545057296753,
  0.03225649893283844,
  0.06731756031513214,
  0.029774991795420647,
  0.01894344575703144],
 'relief': [0.017696550115942955,
  0.0013366510393097997,
  0.001779696554876864,
  0.0026823272928595543,
  0.004011689685285091,
  0.002200922230258584,
  0.0015182681381702423,
  0.016920868307352066,
  0.001741512562148273,
  0.0005848740111105144,
  0.017462190240621567,
  0.000831842829938978,
  0.0014407671988010406,
  0.0034007015638053417,
  0.004264215938746929,
  0.0024914927780628204,
  0.0017900466918945312,
  0.01754544861614704,
  0.0016541248187422752,
  0.0005965306190773845],
 'remorse': [0.022793447598814964,
  0.0013001466868445277,
  0.0007893603760749102,
  0.0022817119024693966,
  0.0017100573750212789,
  0.001585697173140943,
  0.0058026690967381,
  0.00214546755887568,
  0.0019228568999096751,
  0.0004321908636484295,
  0.0219810102134943,
  0.003297799965366721,
  0.0008726639207452536,
  0.0025377641431987286,
  0.0014875258784741163,
  0.0017926559085026383,
  0.005370973609387875,
  0.0018921114969998598,
  0.0017021317034959793,
  0.0004383661434985697],
 'sadness': [0.717038631439209,
  0.0174858421087265,
  0.009665760211646557,
  0.025013301521539688,
  0.011587199755012989,
  0.032516058534383774,
  0.047351233661174774,
  0.05414231866598129,
  0.15950722992420197,
  0.002985563827678561,
  0.7053227424621582,
  0.024937447160482407,
  0.009702421724796295,
  0.015932979062199593,
  0.011700925417244434,
  0.043310295790433884,
  0.05327102541923523,
  0.06065915524959564,
  0.14529092609882355,
  0.0024882855359464884],
 'surprise': [0.02545263059437275,
  0.008590382523834705,
  0.002096200129017234,
  0.00187594722956419,
  0.0035546058788895607,
  0.012824618257582188,
  0.003425491275265813,
  0.06163259223103523,
  0.019992737099528313,
  0.0016339241992682219,
  0.02682442031800747,
  0.020296936854720116,
  0.0022772199008613825,
  0.0019726448226720095,
  0.0032866722904145718,
  0.010770943015813828,
  0.0036063282750546932,
  0.04851242154836655,
  0.031294673681259155,
  0.001302179298363626],
 'neutral': [0.9549601674079895,
  0.96993488073349,
  0.9549601674079895,
  0.9549601674079895,
  0.9677261114120483,
  0.9549601674079895,
  0.9569121599197388,
  0.9549601674079895,
  0.9612938761711121,
  0.9622653722763062,
  0.9391067624092102,
  0.968702495098114,
  0.4781024158000946,
  0.7189856171607971,
  0.9525890946388245,
  0.8253066539764404,
  0.9512789249420166,
  0.18175038695335388,
  0.9513002038002014,
  0.9524426460266113]}

In [19]:
from tqdm import tqdm
from nltk.tokenize import sent_tokenize

emotion_labels = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise",
    "neutral",
]

isbn_list = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn_list.append(books["isbn13"][i])

    # Correct sentence tokenization
    sentences = sent_tokenize(books["description"][i])

    # Get predictions per sentence
    predictions = [classifier(sent)[0] for sent in sentences]

    # Aggregate scores
    max_scores = calculate_max_emotion_scores(predictions)

    # Store for each emotion
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [36:59<00:00,  2.34it/s]

In [21]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn_list

In [22]:
emotions_df.head()

,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,...,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral,isbn13
0,0.774087,0.025069,0.002810,0.009232,0.160479,0.052508,0.002229,0.017478,0.010262,0.032251,...,0.009590,0.008651,0.020319,0.035314,0.017462,0.021981,0.705323,0.026824,0.939107,9780002005883
1,0.883299,0.002410,0.004791,0.020328,0.065462,0.003575,0.440126,0.319999,0.020270,0.024230,...,0.008468,0.009926,0.003875,0.043417,0.000832,0.003298,0.024937,0.020297,0.968702,9780002261982
2,0.862983,0.001516,0.042629,0.037846,0.070031,0.005494,0.004086,0.001433,0.003704,0.026094,...,0.009505,0.011954,0.005273,0.028677,0.001441,0.000873,0.009702,0.002277,0.478102,9780006178736
3,0.234325,0.001594,0.011206,0.015148,0.475431,0.082694,0.004918,0.002604,0.002887,0.013806,...,0.011858,0.012749,0.005644,0.091185,0.003401,0.002538,0.015933,0.001973,0.718986,9780006280897
4,0.856808,0.002812,0.004111,0.012656,0.357381,0.192464,0.108095,0.426400,0.025101,0.013699,...,0.000973,0.437743,0.005499,0.015883,0.004264,0.001488,0.011701,0.003287,0.969808,9780006280934

In [29]:
print(len(isbn_list))
print("-"*10)
print(len(emotions_df))

5197
----------
5197

In [30]:
len(isbn_list), len(emotion_scores["joy"])

(5197, 5197)

In [31]:
emotions_df.shape

(5197, 29)

In [32]:
emotions_df.isna().sum()

admiration        0
amusement         0
anger             0
annoyance         0
approval          0
caring            0
confusion         0
curiosity         0
desire            0
disappointment    0
disapproval       0
disgust           0
embarrassment     0
excitement        0
fear              0
gratitude         0
grief             0
joy               0
love              0
nervousness       0
optimism          0
pride             0
realization       0
relief            0
remorse           0
sadness           0
surprise          0
neutral           0
isbn13            0
dtype: int64

In [33]:
books = pd.merge(books, emotions_df , on = "isbn13")

In [34]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.017703,0.009590,0.008651,0.020319,0.035314,0.017462,0.021981,0.705323,0.026824,0.939107
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.002870,0.008468,0.009926,0.003875,0.043417,0.000832,0.003298,0.024937,0.020297,0.968702
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,0.042396,0.009505,0.011954,0.005273,0.028677,0.001441,0.000873,0.009702,0.002277,0.478102
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,0.237776,0.011858,0.012749,0.005644,0.091185,0.003401,0.002538,0.015933,0.001973,0.718986
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,0.004520,0.000973,0.437743,0.005499,0.015883,0.004264,0.001488,0.011701,0.003287,0.969808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,0.120219,0.009203,0.006277,0.002589,0.053551,0.002932,0.006949,0.675084,0.056024,0.958048
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,0.005663,0.000691,0.015998,0.005065,0.198113,0.003180,0.000943,0.002229,0.004079,0.823268
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.004114,0.001414,0.031367,0.054172,0.063812,0.046676,0.000923,0.004495,0.002844,0.499256
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.002712,0.004655,0.075111,0.015153,0.076801,0.010597,0.008506,0.045973,0.010479,0.879207
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.003974,0.000730,0.912152,0.005680,0.094416,0.002101,0.002537,0.002446,0.002321,0.924508

In [36]:
books.to_csv("books_with_emotions.csv", index= False)